version: "2"

linters:
  enable:
    - errcheck       # check for unchecked errors
    - govet          # go vet checks
    - staticcheck    # staticcheck suite
    - unused         # detect unused code
    - gosimple       # simplification suggestions
    - ineffassign    # detect ineffectual assignments
    - gofmt          # formatting
    - goimports      # import ordering
    - misspell       # catch common typos
    - gocritic       # opinionated style checks
    - noctx          # detect http calls without context
    - bodyclose      # ensure http response bodies are closed
    - contextcheck   # ensure functions receive and forward ctx
    - godot          # ensure comments end with a period
    - exhaustive     # check exhaustive switch statements on enums
    - wrapcheck      # ensure errors from external packages are wrapped

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable:
      - shadow

  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/brian93512/agentsafe

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance

  godot:
    scope: declarations
    capital: false

  exhaustive:
    default-signifies-exhaustive: true

issues:
  exclude-rules:
    # Test files are allowed to have longer functions and skip some checks
    - path: "_test\\.go"
      linters:
        - wrapcheck
        - errcheck
        - godot

    # Stub adapters intentionally return unimplemented errors
    - path: "pkg/adapter/(openai|skills)/adapter\\.go"
      linters:
        - wrapcheck

  max-issues-per-linter: 0
  max-same-issues: 0
