version: "2"

linters:
  default: none
  enable:
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - misspell
    - gocritic
    - noctx
    - bodyclose
    - contextcheck
    - godot
    - exhaustive
    - wrapcheck

  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true

    govet:
      enable:
        - shadow

    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
      disabled-checks:
        - hugeParam   # UnifiedTool is the core value type; pointer refactor is a future task

    godot:
      scope: declarations
      capital: false

    exhaustive:
      default-signifies-exhaustive: true

  exclusions:
    rules:
      - path: "_test\\.go"
        linters:
          - wrapcheck
          - errcheck
          - godot

      - path: "pkg/adapter/(openai|skills)/adapter\\.go"
        linters:
          - wrapcheck

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/brian93512/agentsafe

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
